//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBWebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FriendBookDBEntities : DbContext
    {
        public FriendBookDBEntities()
            : base("name=FriendBookDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FriendsBooksMapping> FriendsBooksMappings { get; set; }
        public virtual DbSet<BooksList> BooksLists { get; set; }
        public virtual DbSet<FriendsList> FriendsLists { get; set; }
    }
}
